version: "3.9"
services:

  spring-api-gateway:
    image: spring-api-gateway
    container_name: spring-api-gateway-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - api-network

networks:
  api-network:
    external: true

volumes:
  mysql-volume:
