version: "3.9"
services:

  spring-api-eureka-server:
    image: spring-api-eureka-server
    container_name: spring-api-eureka-server-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - api-network

networks:
  api-network:
    external: true

volumes:
  mysql-volume:
