version: "3.9"
services:
  mongo:
    image: mongo:7.0
    container_name: mongo-container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb-data:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d:ro
    networks:
      - api-network

volumes:
  mongodb-data:

networks:
  api-network:
    external: true
