version: "3.9"
services:

  spring-api-asignaturas-servicios:
    image: spring-api-asignaturas-servicios
    container_name: spring-api-asignaturas-servicios-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - api-network

networks:
  api-network:
    external: true

volumes:
  mongo-volume:
