version: "3.9"
services:

  spring-api-usuarios-servicios:
    image: spring-api-usuarios-servicios
    container_name: spring-api-usuarios-servicios-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - api-network

networks:
  api-network:
    external: true

volumes:
  mysql-volume:
